#!/usr/bin/env python3
"""v26 atomic config registry (amendment codex #2/#3, frozen).

A config = one row in configs.parquet, generated by this frozen enumerator: axes =
(family_variant, K, hold_band, exit_style, gross_cap, execution, sizing). The enumerator
writes EVERY cell of the 6 x 8 x 4 x 3 x 2 x 3 x 3 = 10,368 full cross with status RUN
or PRUNED(reason_code). The registry sha256 + prune-ledger sha256 are part of
FREEZE-GRID.json and are written BEFORE any test PnL is read.

Pruning (mathematical pre-test rules ONLY, codex #3):
- PRUNED(family_forces_band): the band axis contradicts the family's definitional band
  (empty intersection) or collapses onto an already-running identical cell (dedup rule).
- PRUNED(empty_by_construction): the (family, band) selection filter provably yields 0
  candidates on the TRAIN data of the FIRST fold only (train-only info; the candidate
  count is recorded).
- NO margin-based pruning: every K x sizing x leverage cell RUNs; caps bind inside the
  sim.
Runtime failures are NOT pruned -- they fail closed inside the correction family (D10).
"""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from v26_common import (EXECUTIONS, EXIT_STYLES, FAMILY_VARIANTS, FULL_CROSS, GROSS_CAPS,
                        HOLD_BANDS, K_GRID, SIZINGS, V26_DATA, canonical_sha256,
                        config_id)
from v26_families import allowed_bands

REGISTRY_COLS = ["config_id", "family", "K", "hold_band", "exit_style", "gross_cap",
                 "execution", "sizing", "status", "prune_reason",
                 "fold1_train_candidates"]


def enumerate_registry(fold1_candidate_counts: dict[tuple[str, str], int]) -> pd.DataFrame:
    """Full-cross enumeration. fold1_candidate_counts: {(family, band): n ranked
    candidates on fold-1 TRAIN} for every band-RUN cell (from v26_families on the cached
    fold-1 artifacts)."""
    rows = []
    for fam in FAMILY_VARIANTS:
        bands = allowed_bands(fam)
        for band in HOLD_BANDS:
            band_status = bands[band]
            if band_status == "RUN":
                n_cand = fold1_candidate_counts.get((fam, band))
                if n_cand is None:
                    raise ValueError(f"missing fold-1 candidate count for RUN cell "
                                     f"({fam}, {band}) -- registry cannot enumerate")
                if n_cand == 0:
                    status, reason = "PRUNED", "empty_by_construction"
                else:
                    status, reason = "RUN", ""
            else:
                status, reason, n_cand = "PRUNED", band_status, -1
            for k in K_GRID:
                for ex in EXIT_STYLES:
                    for g in GROSS_CAPS:
                        for e in EXECUTIONS:
                            for s in SIZINGS:
                                rows.append({
                                    "config_id": config_id(fam, k, band, ex, g, e, s),
                                    "family": fam, "K": k, "hold_band": band,
                                    "exit_style": ex, "gross_cap": g, "execution": e,
                                    "sizing": s, "status": status,
                                    "prune_reason": reason,
                                    "fold1_train_candidates": int(n_cand),
                                })
    df = pd.DataFrame(rows, columns=REGISTRY_COLS).sort_values(
        "config_id", kind="mergesort").reset_index(drop=True)
    assert len(df) == FULL_CROSS, f"registry cell count {len(df)} != {FULL_CROSS}"
    assert df["config_id"].is_unique
    return df


def write_registry(registry: pd.DataFrame, out_dir: Path = V26_DATA) -> dict:
    """Write configs.parquet + prune_ledger.parquet + registry_sha.json.
    Returns {'registry_sha256', 'prune_ledger_sha256', counts...}."""
    out_dir.mkdir(parents=True, exist_ok=True)
    registry.to_parquet(out_dir / "configs.parquet", index=False)
    ledger = registry[registry["status"] == "PRUNED"].reset_index(drop=True)
    ledger.to_parquet(out_dir / "prune_ledger.parquet", index=False)
    meta = {
        "registry_sha256": canonical_sha256(registry),
        "prune_ledger_sha256": canonical_sha256(ledger),
        "n_cells": int(len(registry)),
        "n_run": int((registry["status"] == "RUN").sum()),
        "n_pruned": int(len(ledger)),
        "prune_reason_counts": ledger["prune_reason"].value_counts().to_dict(),
    }
    with open(out_dir / "registry_sha.json", "w") as fh:
        json.dump(meta, fh, indent=2)
    return meta


def load_registry(out_dir: Path = V26_DATA) -> pd.DataFrame:
    p = out_dir / "configs.parquet"
    if not p.exists():
        raise FileNotFoundError(f"registry missing: {p} -- build it first")
    return pd.read_parquet(p)
