#!/usr/bin/env python3
"""HL Copy Trader V16 -- top-decile faithful copy on liquid majors (the validated strategy).

Strategy: projects/quant/v16/strategy. Build spec: projects/quant/v16/go-live-spec.
Validation: projects/quant/decisions/2026-06-11-copy-ship-to-shadow-codex-gate (+8-9bps OOS taker median).

This is a THIN, FAIL-FAST wrapper around the battle-tested V15 engine (hl_copy_trader_v15.CopyTrader:
proportional/fixed sizing, margin gates, latched global stop, position recovery, exchange-truth PnL,
2026-05/06 codex fixes). V16 adds exactly three things -- nothing else may diverge from the base engine:

  1. LIQUID WHITELIST HARD GUARD (the microcap artifact lived outside it). Enforced at BOTH choke
     points: _on_hl_trade (signal path) and _enter_position (order path, defense in depth). The
     whitelist must EXACTLY equal the validated LIQUID set (l2_calib_10coin.json keys) -- asserted.
  2. V16 Mongo collections (v16_*) -- clean attribution, separate from V11/V15 history.
  3. FAITHFUL-COPY CONFIG ASSERTS, fail-fast at startup: fixed sizing (matches the equal-weighted
     per-trade validation), instant entry, FIRST_CLOSE exit, trailing TP present (hard rule #7),
     SL floor, addon disabled, cohort metadata present.

Run: python strategies/live/hl_copy_trader_v16.py --config config/copy_trader_wallets_v16.json
     (--shadow supported for the plumbing replay check; live launch only after the codex gate)
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
_REPO = _HERE.parent.parent

import hl_copy_trader_v15 as base  # noqa: E402

# ── V16 collections (module-level globals in the base engine; rebind BEFORE instantiation) ──────────
base.DB_COLLECTION = "v16_copy_trades"
base.DB_SHADOW_COLLECTION = "v16_shadow_signals"
base.DB_FILLS_COLLECTION = "v16_target_fills"
base.DB_OPEN_POSITIONS = "v16_open_positions"
base.DB_EXCHANGE_FILLS = "v16_exchange_fills"
base.DB_ORDER_IDS = "v16_order_ids"

logger = base.logging.getLogger("hl_copy_v16")

L2_CALIB = _REPO / "app" / "data" / "v15" / "l2_calib_10coin.json"


class V16CopyTrader(base.CopyTrader):
    """V15 engine + liquid whitelist guard + faithful-copy config asserts."""

    def __init__(self, config_path: str, order_size_override: float = None, shadow: bool = False):
        super().__init__(config_path, order_size_override=order_size_override, shadow=shadow)

        g, d = self.global_config, self.default_config

        # ── 1. whitelist: present, and EXACTLY the validated liquid set ─────────────────────────────
        wl = g.get("coin_whitelist")
        if not wl:
            raise ValueError("V16: global.coin_whitelist is REQUIRED (liquid majors hard guard)")
        self.coin_whitelist = set(wl)
        validated = set(json.load(open(L2_CALIB)).keys())
        if self.coin_whitelist != validated:
            raise ValueError(
                f"V16: coin_whitelist != validated LIQUID set. "
                f"extra={sorted(self.coin_whitelist - validated)} missing={sorted(validated - self.coin_whitelist)}. "
                f"Changing the universe voids the validation -- new codex gate required."
            )

        # ── 2. faithful-copy mechanic asserts (any violation = not the validated strategy) ──────────
        def _req(cond: bool, msg: str):
            if not cond:
                raise ValueError(f"V16 CONFIG VIOLATION: {msg}")

        _req(g.get("sizing_mode") == "fixed",
             "sizing_mode must be 'fixed' (validation equal-weights trades; prop split < $10 min order)")
        _req(10.0 <= float(g.get("order_size_usd", 0)) <= 25.0,
             "order_size_usd must be in [10, 25] for the $50-200 go-live stage")
        _req(d.get("entry_mode") == "instant", "entry_mode must be 'instant' (leader open -> taker entry)")
        _req(d.get("exit_type") == "FIRST_CLOSE", "exit_type must be FIRST_CLOSE (faithful exit)")
        _req(int(d.get("max_addon_multiplier", 99)) <= 1,
             "max_addon_multiplier must be <=1 (copy the round-trip OPEN once; no stacking at $12)")
        _req(d.get("trail_activate_bps") is not None and d.get("trail_bps") is not None,
             "trailing TP required on every position (hard rule #7)")
        _req(d.get("sl_bps") is not None and float(d["sl_bps"]) < 0, "protective sl_bps < 0 required")
        _req(0 < float(g.get("max_margin_util", 1)) <= 0.6,
             "max_margin_util must be <= 0.6 at go-live size")
        _req(0 < float(g.get("global_stop_pct", 0)) <= 0.08,
             "global_stop_pct must be set (latched flatten-all) and <= 8%")
        _req(float(g.get("gross_backstop_x", 1e9)) <= 2.0, "gross_backstop_x must be <= 2.0 at go-live")
        _req(g.get("cohort_asof") is not None,
             "cohort_asof missing -- config must be generated by research/v16/select_cohort.py")
        n_wallets = len(self.wallet_configs)
        _req(n_wallets >= 30, f"cohort {n_wallets} < 30 minimum (re-run selection)")
        _req(n_wallets <= 100, f"cohort {n_wallets} > 100 cap")

        # ── 3. feed scope: subscribe trades ONLY for whitelist coins (base subscribes everything).
        # Aligns the WS feed with the guard; no builder-dex (xyz:/flx:) coins in V16 at all.
        self.all_perp_coins = [c for c in self.all_perp_coins if c in self.coin_whitelist]
        self.all_builder_coins = []
        missing_feed = self.coin_whitelist - set(self.all_perp_coins)
        if missing_feed:
            raise ValueError(f"V16: whitelist coins missing from HL perp universe: {sorted(missing_feed)}")

        self._v16_blocked_signals = 0
        logger.info(
            f"V16 READY: cohort={n_wallets} wallets (asof {g['cohort_asof']}), "
            f"whitelist={sorted(self.coin_whitelist)}, order=${self.order_size:.0f} fixed, "
            f"margin_util<={g['max_margin_util']}, stop={g['global_stop_pct']:.0%} latched, "
            f"gross_backstop={g['gross_backstop_x']}x, trail={d['trail_activate_bps']}/{d['trail_bps']}bps, "
            f"sl={d['sl_bps']}bps, shadow={self.shadow_mode}"
        )

    # ── choke point 1: signal path -- drop non-whitelist coins before any processing ────────────────
    def _on_hl_trade(self, trade: dict):
        coin = trade.get("coin", "")
        if coin not in self.coin_whitelist:
            # Cheap pre-check: only count drops that involve a target wallet (else it is just market noise)
            users = trade.get("users", [])
            if len(users) >= 2 and (users[0].lower() in self.target_set or users[1].lower() in self.target_set):
                self._v16_blocked_signals += 1
                if self._v16_blocked_signals % 50 == 1:
                    logger.info(f"V16 GUARD: dropped target signal on non-whitelist coin {coin} "
                                f"(total dropped: {self._v16_blocked_signals})")
            return
        return super()._on_hl_trade(trade)

    # ── choke point 2: order path -- nothing outside the whitelist can ever reach the exchange ──────
    async def _enter_position(self, coin: str, is_buy: bool, twap_dedup_key=None, wallet: str = None,
                              skip_cooldown: bool = False):
        if coin not in self.coin_whitelist:
            logger.error(f"V16 GUARD BREACH BLOCKED: _enter_position called for non-whitelist {coin} "
                         f"(wallet={wallet}) -- investigate the caller")
            base._tg(f"V16 GUARD: blocked non-whitelist entry attempt {coin}")
            return
        return await super()._enter_position(coin, is_buy, twap_dedup_key=twap_dedup_key,
                                             wallet=wallet, skip_cooldown=skip_cooldown)


def main():
    import argparse
    ap = argparse.ArgumentParser(description="HL Copy Trader V16 -- top-decile faithful copy (liquid majors)")
    ap.add_argument("--config", default="config/copy_trader_wallets_v16.json")
    ap.add_argument("--size", type=float, default=None, help="order size override (USD)")
    ap.add_argument("--shadow", action="store_true", help="no real orders (plumbing replay / smoke)")
    args = ap.parse_args()

    config_path = args.config
    if not Path(config_path).is_absolute():
        config_path = str(_REPO / config_path)
    if not Path(config_path).exists():
        logger.error(f"V16 config not found: {config_path} -- run research/v16/select_cohort.py first")
        sys.exit(1)

    trader = V16CopyTrader(config_path, order_size_override=args.size, shadow=args.shadow)
    # Reuse the base engine's run loop wholesale (WS, exits, reconcile, stats, shutdown).
    base.asyncio.run(trader.run())


if __name__ == "__main__":
    main()
