#!/usr/bin/env python3
"""HL Copy Trader V16 -- top-decile faithful copy on liquid majors (the validated strategy).

Strategy: projects/quant/v16/strategy. Build spec: projects/quant/v16/go-live-spec.
Validation: projects/quant/decisions/2026-06-11-copy-ship-to-shadow-codex-gate (+8-9bps OOS taker median).

This is a THIN, FAIL-FAST wrapper around the battle-tested V15 engine (hl_copy_trader_v15.CopyTrader:
proportional/fixed sizing, margin gates, latched global stop, position recovery, exchange-truth PnL,
2026-05/06 codex fixes). V16 adds exactly three things -- nothing else may diverge from the base engine:

  1. LIQUID WHITELIST HARD GUARD (the microcap artifact lived outside it). Enforced at BOTH choke
     points: _on_hl_trade (signal path) and _enter_position (order path, defense in depth). The
     whitelist must EXACTLY equal the validated LIQUID set (l2_calib_10coin.json keys) -- asserted.
  2. V16 Mongo collections (v16_*) -- clean attribution, separate from V11/V15 history.
  3. FAITHFUL-COPY CONFIG ASSERTS, fail-fast at startup: fixed sizing (matches the equal-weighted
     per-trade validation), instant entry, FIRST_CLOSE exit, trailing TP present (hard rule #7),
     SL floor, addon disabled, cohort metadata present.

Run: python strategies/live/hl_copy_trader_v16.py --config config/copy_trader_wallets_v16.json
     (--shadow supported for the plumbing replay check; live launch only after the codex gate)
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
_REPO = _HERE.parent.parent

import hl_copy_trader_v15 as base  # noqa: E402

# ── V16 collections (module-level globals in the base engine; rebind BEFORE instantiation) ──────────
base.DB_COLLECTION = "v16_copy_trades"
base.DB_SHADOW_COLLECTION = "v16_shadow_signals"
base.DB_FILLS_COLLECTION = "v16_target_fills"
base.DB_OPEN_POSITIONS = "v16_open_positions"
base.DB_EXCHANGE_FILLS = "v16_exchange_fills"
base.DB_ORDER_IDS = "v16_order_ids"

logger = base.logging.getLogger("hl_copy_v16")

L2_CALIB = _REPO / "app" / "data" / "v15" / "l2_calib_10coin.json"


class V16CopyTrader(base.CopyTrader):
    """V15 engine + liquid whitelist guard + faithful-copy config asserts."""

    def __init__(self, config_path: str, order_size_override: float = None, shadow: bool = False):
        super().__init__(config_path, order_size_override=order_size_override, shadow=shadow)

        g, d = self.global_config, self.default_config

        # ── 1. whitelist: present, and EXACTLY the validated liquid set ─────────────────────────────
        wl = g.get("coin_whitelist")
        if not wl:
            raise ValueError("V16: global.coin_whitelist is REQUIRED (liquid majors hard guard)")
        self.coin_whitelist = set(wl)
        validated = set(json.load(open(L2_CALIB)).keys())
        if self.coin_whitelist != validated:
            raise ValueError(
                f"V16: coin_whitelist != validated LIQUID set. "
                f"extra={sorted(self.coin_whitelist - validated)} missing={sorted(validated - self.coin_whitelist)}. "
                f"Changing the universe voids the validation -- new codex gate required."
            )

        # ── 2. faithful-copy mechanic asserts (any violation = not the validated strategy) ──────────
        def _req(cond: bool, msg: str):
            if not cond:
                raise ValueError(f"V16 CONFIG VIOLATION: {msg}")

        _req(g.get("sizing_mode") == "fixed",
             "sizing_mode must be 'fixed' (validation equal-weights trades; prop split < $10 min order)")
        _req(10.0 <= float(g.get("order_size_usd", 0)) <= 200.0,
             "order_size_usd must be in [10, 200] (Alberto 2026-06-11: full account, up to 10x liquid)")
        _req(d.get("entry_mode") == "instant", "entry_mode must be 'instant' (leader open -> taker entry)")
        _req(d.get("exit_type") == "FIRST_CLOSE", "exit_type must be FIRST_CLOSE (faithful exit)")
        _req(int(d.get("max_addon_multiplier", 99)) <= 1,
             "max_addon_multiplier must be <=1 (copy the round-trip OPEN once; no stacking at $12)")
        _req(d.get("trail_activate_bps") is not None and d.get("trail_bps") is not None,
             "trailing TP required on every position (hard rule #7)")
        _req(d.get("sl_bps") is not None and float(d["sl_bps"]) < 0, "protective sl_bps < 0 required")
        _req(0 < float(g.get("max_margin_util", 1)) <= 0.7,
             "max_margin_util must be <= 0.7")
        _req(0 < float(g.get("global_stop_pct", 0)) <= 0.15,
             "global_stop_pct must be set (latched flatten-all) and <= 15%")
        _req(float(g.get("gross_backstop_x", 1e9)) <= 8.0, "gross_backstop_x must be <= 8.0")
        _req(g.get("cohort_asof") is not None,
             "cohort_asof missing -- config must be generated by research/v16/select_cohort.py")
        # codex gate 2026-06-11 finding #2 (BLOCK): FULL-CLOSE semantics. With exit_min_trim_pct >= 0.8
        # and a huge exit_twap_min_notional, the engine's FIRST_CLOSE machinery only acts when the
        # leader has closed >= 80% of tracked notional (full exit at >= 90%) -- the validated
        # full-close exit, not a 5%-reverse-flow trim.
        _req(float(g.get("exit_min_trim_pct", 0)) >= 0.80,
             "exit_min_trim_pct must be >= 0.80 (full-close exit semantics, codex finding #2)")
        _req(float(d.get("exit_twap_min_notional", 0)) >= 1e8,
             "exit_twap_min_notional must be huge (disable $-threshold trims, codex finding #2)")
        _req(abs(float(g.get("full_exit_trim_pct", 0.90)) - float(g["exit_min_trim_pct"])) < 1e-9,
             "full_exit_trim_pct must equal exit_min_trim_pct (no partial-trim band; codex r2 #2)")
        n_wallets = len(self.wallet_configs)
        _req(n_wallets >= 30, f"cohort {n_wallets} < 30 minimum (re-run selection)")
        _req(n_wallets <= 100, f"cohort {n_wallets} > 100 cap")

        # ── 3. feed scope: subscribe trades ONLY for whitelist coins (base subscribes everything).
        # Aligns the WS feed with the guard; no builder-dex (xyz:/flx:) coins in V16 at all.
        self.all_perp_coins = [c for c in self.all_perp_coins if c in self.coin_whitelist]
        self.all_builder_coins = []
        missing_feed = self.coin_whitelist - set(self.all_perp_coins)
        if missing_feed:
            raise ValueError(f"V16: whitelist coins missing from HL perp universe: {sorted(missing_feed)}")

        self._v16_blocked_signals = 0
        self._v16_add_fills = 0
        self._v16_suppressed_reverse = 0

        # ── codex r2 blocker #1: UNCONDITIONAL leader-position tracker. The base engine updates its
        # _target_positions only when an entry actually proceeds, so a guard-rejected open makes the
        # leader's next add look like a fresh open (and a later close look like an open of the other
        # side). V16 classifies every fill against THIS tracker, which is updated for every target
        # fill on a whitelisted coin regardless of whether we copied it. Seeded from the startup REST
        # snapshot (base _init_target_positions ran in super().__init__).
        self._v16_leader_pos = {}
        for addr, posmap in self._target_positions.items():
            for cn, sz in posmap.items():
                if cn in self.coin_whitelist and abs(sz) > 1e-12:
                    self._v16_leader_pos[(addr, cn)] = float(sz)

        # ── 4. label + PnL epoch (Alberto msg 9222: "pnl report with updated labels and epoch start").
        # Epoch = first LIVE start, persisted once in Mongo v16_meta; all PnL/report numbers count from
        # there (base fill-sync reads self.pnl_epoch_ms). Shadow runs use 'now' without persisting.
        self.label = "V16"
        now_ms = int(base.time.time() * 1000)
        if self.shadow_mode:
            self.pnl_epoch_ms = now_ms
        else:
            self.db.v16_meta.update_one(
                {"_id": "epoch"}, {"$setOnInsert": {"epoch_ms": now_ms,
                                                    "created_at": base.datetime.now(base.timezone.utc)}},
                upsert=True)
            self.pnl_epoch_ms = int(self.db.v16_meta.find_one({"_id": "epoch"})["epoch_ms"])
        logger.info(f"V16 PnL epoch: {base.datetime.fromtimestamp(self.pnl_epoch_ms/1000, base.timezone.utc)}")

        logger.info(
            f"V16 READY: cohort={n_wallets} wallets (asof {g['cohort_asof']}), "
            f"whitelist={sorted(self.coin_whitelist)}, order=${self.order_size:.0f} fixed, "
            f"margin_util<={g['max_margin_util']}, stop={g['global_stop_pct']:.0%} latched, "
            f"gross_backstop={g['gross_backstop_x']}x, trail={d['trail_activate_bps']}/{d['trail_bps']}bps, "
            f"sl={d['sl_bps']}bps, shadow={self.shadow_mode}"
        )

    # ── choke point 1: signal path ───────────────────────────────────────────────────────────────────
    # a) drop non-whitelist coins before any processing (liquid hard guard)
    # b) classify leader ADD fills (same direction as their tracked position): TRACK them into
    #    _target_positions + _position_accumulated but NEVER copy them. Fixes codex finding #3 (with
    #    max_addon_multiplier=1 the base engine skips adds WITHOUT updating state, so a later partial
    #    close looks like a near-full close and ejects us early) AND enforces entry purity: V16 enters
    #    ONLY on true 0->nonzero leader opens (the validated round-trip definition).
    def _on_hl_trade(self, trade: dict):
        coin = trade.get("coin", "")
        if coin not in self.coin_whitelist:
            users = trade.get("users", [])
            if len(users) >= 2 and (users[0].lower() in self.target_set or users[1].lower() in self.target_set):
                self._v16_blocked_signals += 1
                if self._v16_blocked_signals % 50 == 1:
                    logger.info(f"V16 GUARD: dropped target signal on non-whitelist coin {coin} "
                                f"(total dropped: {self._v16_blocked_signals})")
            return

        users = trade.get("users", [])
        if len(users) >= 2:
            buyer, seller = users[0].lower(), users[1].lower()
            w = buyer if buyer in self.target_set else (seller if seller in self.target_set else None)
            if w is not None:
                is_buy = (w == buyer)
                wallet = self.leader_to_vault.get(w, w)
                px = float(trade.get("px", 0) or 0)
                sz = float(trade.get("sz", 0) or 0)
                if px <= 0 or sz <= 0:
                    return
                key = (wallet, coin)
                prev = self._v16_leader_pos.get(key, 0.0)          # UNCONDITIONAL tracker (codex r2 #1)
                signed = sz if is_buy else -sz
                prev_notional = abs(prev) * px
                is_open = prev_notional < 1.0
                is_add = (not is_open) and ((prev > 0) == is_buy)
                we_hold = any(p['coin'] == coin and p.get('wallet') == wallet and p.get('filled')
                              for p in self.positions)

                if is_add:
                    # ADD: track, never copy -- even when the original open was guard-rejected
                    tid = trade.get("tid", "")
                    if tid:
                        if tid in self._seen_tids:
                            return
                        self._seen_tids[tid] = base.time.time()
                    self._v16_leader_pos[key] = prev + signed
                    self._target_positions.setdefault(wallet, {})[coin] = self._v16_leader_pos[key]
                    if we_hold:
                        self._position_accumulated[key] = self._position_accumulated.get(key, 0.0) + sz * px
                    self._v16_add_fills += 1
                    try:
                        self.db[base.DB_FILLS_COLLECTION].insert_one({
                            "wallet": wallet, "coin": coin, "side": "BUY" if is_buy else "SELL",
                            "price": px, "size": sz, "notional": sz * px,
                            "wallet_group": self.wallet_groups.get(wallet, "unknown"),
                            "market_type": "perp", "v16_class": "add_tracked_not_copied",
                            "timestamp": base.datetime.now(base.timezone.utc),
                            "ts_epoch": base.time.time(),
                        })
                    except Exception:
                        pass
                    return

                if (not is_open) and (not is_add) and not we_hold:
                    # REVERSE on a position we never copied (e.g. the open was guard-rejected): track
                    # only, NEVER pass to the base handler -- its own (stale) view would classify this
                    # as an opening trade and copy the leader's CLOSE as our OPEN (codex r2 #1).
                    tid = trade.get("tid", "")
                    if tid:
                        if tid in self._seen_tids:
                            return
                        self._seen_tids[tid] = base.time.time()
                    self._v16_leader_pos[key] = prev + signed
                    self._target_positions.setdefault(wallet, {})[coin] = self._v16_leader_pos[key]
                    self._v16_suppressed_reverse += 1
                    return

                # OPEN (leader ~flat) or REVERSE-while-we-hold: update tracker, hand to the base
                # engine (entry guards / exit-TWAP machinery). Base may also update its own
                # _target_positions on a copied open; ours is authoritative for classification.
                # Dedup: CHECK (without consuming) -- the base handler inserts the tid itself.
                tid = trade.get("tid", "")
                if tid and tid in self._seen_tids:
                    return
                self._v16_leader_pos[key] = prev + signed
        return super()._on_hl_trade(trade)

    # ── choke point 2: order path -- nothing outside the whitelist can ever reach the exchange ──────
    async def _enter_position(self, coin: str, is_buy: bool, twap_dedup_key=None, wallet: str = None,
                              skip_cooldown: bool = False):
        if coin not in self.coin_whitelist:
            logger.error(f"V16 GUARD BREACH BLOCKED: _enter_position called for non-whitelist {coin} "
                         f"(wallet={wallet}) -- investigate the caller")
            base._tg(f"V16 GUARD: blocked non-whitelist entry attempt {coin}")
            return
        return await super()._enter_position(coin, is_buy, twap_dedup_key=twap_dedup_key,
                                             wallet=wallet, skip_cooldown=skip_cooldown)

    # ── codex finding #4: TAKER/IOC exits for V16. The base engine posts a maker (ALO) exit and waits
    # up to 60s before IOC fallback -- unmodeled delay + adverse selection, worst on SL/trail exits.
    # The validation prices exits as immediate taker. Pre-setting the maker-state flags routes the base
    # state machine straight to its IOC block (escalating-slip IOC, fill-verified) for EVERY exit.
    async def _exit_position(self, pos: dict, trim_size: float = None) -> bool:
        if not pos.get('_maker_exit_tried'):
            pos['_maker_exit_tried'] = True       # skip the ALO leg entirely
            pos['_maker_exit_time'] = 0.0         # elapsed >= 60s instantly -> IOC path now
        return await super()._exit_position(pos, trim_size=trim_size)


def main():
    import argparse
    ap = argparse.ArgumentParser(description="HL Copy Trader V16 -- top-decile faithful copy (liquid majors)")
    ap.add_argument("--config", default="config/copy_trader_wallets_v16.json")
    ap.add_argument("--size", type=float, default=None, help="order size override (USD)")
    ap.add_argument("--shadow", action="store_true", help="no real orders (plumbing replay / smoke)")
    args = ap.parse_args()

    config_path = args.config
    if not Path(config_path).is_absolute():
        config_path = str(_REPO / config_path)
    if not Path(config_path).exists():
        logger.error(f"V16 config not found: {config_path} -- run research/v16/select_cohort.py first")
        sys.exit(1)

    trader = V16CopyTrader(config_path, order_size_override=args.size, shadow=args.shadow)
    # Reuse the base engine's run loop wholesale (WS, exits, reconcile, stats, shutdown).
    base.asyncio.run(trader.run())


if __name__ == "__main__":
    main()
